name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env
          echo TOKEN=${{ secrets.TOKEN }} >> .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo GUILD_ID=${{ secrets.GUILD_ID }} >> .env
          echo MEGA_EMAIL=${{ secrets.MEGA_EMAIL }} >> .env
          echo MEGA_PASSWORD=${{ secrets.MEGA_PASSWORD }} >> .env
          echo MEGA_DIR=${{ secrets.MEGA_DIR }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          cat .env

      - name: Docker run
        run: docker-compose up -d --force-recreate --build
